(() => {
  const API_BASE = window.API_BASE || '';
  const tokenKey = 'finance-rag-auth-token'; let signup = false;
  const button = document.querySelector('#authButton'), modal = document.querySelector('#authModal');
  const form = document.querySelector('#authForm'), status = document.querySelector('#authStatus');
  const switcher = document.querySelector('#authSwitch'), nameField = document.querySelector('#authNameField');
  if (!button || !modal || !form || !status || !switcher || !nameField) return;
  const auth = () => localStorage.getItem(tokenKey);
  const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${auth()}` });
  function show(open) { modal.hidden = !open; document.body.classList.toggle('modal-open', open); }
  function updateButton(user) { button.innerHTML = user ? '<i class="fa-solid fa-right-from-bracket"></i> 로그아웃' : '<i class="fa-solid fa-user"></i> 로그인'; button.title = user ? `${user.display_name}님으로 로그인됨 · 클릭하면 로그아웃` : ''; button.dataset.loggedIn = user ? 'true' : ''; }
  async function restore() { if (!auth()) return; const r = await fetch(`${API_BASE}/auth/me`, { headers: headers() }); if (r.ok) updateButton(await r.json()); else localStorage.removeItem(tokenKey); }
  button.addEventListener('click', async () => { if (button.dataset.loggedIn) { await fetch(`${API_BASE}/auth/logout`, { method: 'POST', headers: headers() }); localStorage.removeItem(tokenKey); updateButton(); return; } show(true); });
  document.querySelectorAll('[data-auth-close]').forEach(x => x.addEventListener('click', () => show(false)));
  switcher.addEventListener('click', () => { signup = !signup; nameField.hidden = !signup; document.querySelector('#authTitle').textContent = signup ? '회원가입' : '로그인'; form.querySelector('button').textContent = signup ? '가입하고 시작하기' : '로그인'; switcher.textContent = signup ? '이미 계정이 있어요' : '회원가입'; });
  form.addEventListener('submit', async e => { e.preventDefault(); status.textContent = ''; const body = { email: authEmail.value, password: authPassword.value, ...(signup ? { display_name: authName.value } : {}) }; const r = await fetch(`${API_BASE}/auth/${signup ? 'signup' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) { status.textContent = data.detail || '처리하지 못했습니다.'; return; } localStorage.setItem(tokenKey, data.token); updateButton(data.user); show(false); decorateCalendar(); });
  async function decorateCalendar() { const page = document.querySelector('.calendar-page'); if (!page || page.querySelector('.personal-schedule')) return; const section = document.createElement('section'); section.className = 'personal-schedule'; section.innerHTML = auth() ? '<h2>내 일정</h2><form><input type="date" required><input placeholder="일정 제목" required maxlength="160"><button class="btn-primary">추가</button></form><div class="personal-events"></div>' : '<p>개인 일정을 관리하려면 로그인하세요.</p>'; page.querySelector('.calendar-page-head').after(section); if (!auth()) return; const list = section.querySelector('.personal-events'); const load = async () => { const r = await fetch(`${API_BASE}/auth/calendar-events`, { headers: headers() }); if (!r.ok) return; const events = await r.json(); list.innerHTML = events.map(e => `<span>${e.event_date} · ${e.title}<button data-id="${e.id}">삭제</button></span>`).join('') || '<small>등록된 개인 일정이 없습니다.</small>'; list.querySelectorAll('button').forEach(b => b.onclick = async () => { await fetch(`${API_BASE}/auth/calendar-events/${b.dataset.id}`, { method:'DELETE', headers:headers() }); load(); }); }; section.querySelector('form').onsubmit = async e => { e.preventDefault(); const [date,title] = e.target.querySelectorAll('input'); await fetch(`${API_BASE}/auth/calendar-events`, { method:'POST', headers:headers(), body:JSON.stringify({event_date:date.value,title:title.value}) }); e.target.reset(); load(); }; load(); }
  new MutationObserver(decorateCalendar).observe(document.querySelector('#messages'), { childList: true }); restore(); decorateCalendar();
})();
